# Generated by Django 2.2.16 on 2022-03-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220313_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-pub_date',)},
        ),
    ]
